# Solutions to the Background Quiz

In [1]:
import math # for sqrt()
import numpy as np

### Probability

Store the life table in an array so that `lifeTable[j]` is the number of men who survive to `j*10` years of age.

In [2]:
lifeTable = np.array([1000, 959, 952, 938, 920, 876, 758, 524, 211, 22, 0])

In [3]:
# (1) P( newborn lives to 40)
q1Prob = lifeTable[4] / lifeTable[0]
print( q1Prob )

0.92


In [4]:
# (2) P( newborn will die in 20's)
# Begin by computing the number who die in each decade
deathsPerDecade = lifeTable[0:10] - lifeTable[1:11]
print(deathsPerDecade)

# Now compute the probability requested
q2Prob = deathsPerDecade[2] / lifeTable[0]
print( q2Prob )

[ 41   7  14  18  44 118 234 313 189  22]
0.014


In [5]:
# (3) P( man libes to 80 | he is 50 )
q3Prob = lifeTable[8] / lifeTable[5]
print( q3Prob )

0.2408675799086758


In [6]:
# (4) Expected number of points when rolling a weighted die
dieProbs = [1/10, 1/10, 1/10, 1/10, 1/10, 1/2]
oneRollExpectation = 0 
for j in range(0,6):
    oneRollExpectation = oneRollExpectation + (j+1)*dieProbs[j]
    
print( oneRollExpectation )
twoRollExpectation = 2 * oneRollExpectation
print(twoRollExpectation )

4.5
9.0


In [7]:
# (5) P( group of five agriculture students includes two men)
from scipy.stats import binom # use available packages
print( binom.pmf( 2, 5, 0.2 ) ) # pmf means "probability mass function"
print( 128 / 625 ) # the exact result

0.20479999999999998
0.2048


In [8]:
# (6) Bayes at a burger joint
pAshaComesIn = 1/2
pBobComesIn = 1/2

pBurgerGivenAsha = 1/5 
pBurgerGivenBob = 1

pBurger = (pBurgerGivenAsha * pAshaComesIn) + (pBurgerGivenBob * pBobComesIn)

pAshaGivenBurger = (pBurgerGivenAsha * pAshaComesIn) / pBurger
pBobGivenBurger = (pBurgerGivenBob * pBobComesIn) / pBurger
print( pAshaGivenBurger, pBobGivenBurger)

0.16666666666666669 0.8333333333333334


### Linear Algebra

In [9]:
# Build all the vectors and matrices
u = np.array([[2],[3],[1]])
v = np.array([[5],[1],[3]])
w = np.array([[4],[4]])
L = np.array([[2,0,4],[5,3,0],[1,1,1]])
M = np.array([[4,1],[4,2],[1,3]])
R = np.array([[1,0.5],[0.5,1]])

The transpose of a vector *v* is written `v.T`, while the matrix product is written with an `@`.

In [10]:
# (11)
(v.T)@w

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [11]:
# (12)
(v.T)@u

array([[16]])

In [12]:
# (13)
M@w

array([[20],
       [24],
       [16]])

In [13]:
# (14)
u@(w.T)

array([[ 8,  8],
       [12, 12],
       [ 4,  4]])

In [14]:
# (15)
(v.T)@(L@u)

array([[77]])

In [15]:
# (16)
((u-v).T)@M

array([[-6, -5]])

In [16]:
# (17)
print( 9 + math.sqrt(14) )
np.linalg.norm(u,2) + np.linalg.norm(u,1) + np.linalg.norm(u,np.inf)

12.74165738677394


12.74165738677394

In [17]:
# (18)
np.linalg.inv(R)

array([[ 1.33333333, -0.66666667],
       [-0.66666667,  1.33333333]])

In [18]:
# (19)
evals, evects = np.linalg.eig(R)
evals

array([1.5, 0.5])

In [19]:
# (20) 
# Any nonzero multiple of an eigenvector is also an eigenvector
myEvect = math.sqrt(2) * evects[1]
print( myEvect )
R@myEvect

[1. 1.]


array([1.5, 1.5])